version: "3.8"

services:
  kafka:
    image: apache/kafka-native:4.1.1
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      # Two listeners: INTERNAL for Docker network, EXTERNAL for host
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:19092,EXTERNAL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:19092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
    networks:
      - kafka-spark-net

  pyspark-notebook:
    image: quay.io/jupyter/pyspark-notebook
    container_name: pyspark_notebook
    user: root
    ports:
      - "8888:8888"
      - "4040:4040"
      - "4041:4041"
    # Replace UID and GUID with results of bash `id` command
    environment:
      - NB_UID=1001
      - NB_GID=1001
      - CHOWN_HOME=yes
      - CHOWN_EXTRA=/home/jovyan/jobs,/home/jovyan/data,/home/jovyan/work
    volumes:
      - ./notebooks:/home/jovyan/work
      - ./jobs:/home/jovyan/jobs
      - ./data:/home/jovyan/data
    networks:
      - kafka-spark-net
    depends_on:
      - kafka

networks:
  kafka-spark-net:
    driver: bridge
